[package]
name = "swaysettings"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
clap.workspace = true

swaysettings-core = { path = "../core" }

glib.workspace = true
gio.workspace = true
gtk4.workspace = true
libadwaita.workspace = true
gdk4.workspace = true
regex.workspace = true
libc.workspace = true
once_cell.workspace = true
udisks2 = "0.3.1"
whoami.workspace = true
