[package]
name = "swaysettings-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
once_cell.workspace = true
log.workspace = true

# GNOME stack
glib.workspace = true
gio.workspace = true
gdk4.workspace = true
gsk4.workspace = true
graphene.workspace = true
gtk4.workspace = true
gdk-pixbuf.workspace = true
libc.workspace = true

[build-dependencies]
glib-build-tools = "0.22.0-alpha.2"
grass = "0.13"
