use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use gdk4::prelude::TextureExtManual;
use gio::prelude::*;
use glib::{self, Variant, VariantTy};

use crate::constants;
use crate::utils;

#[derive(Debug, thiserror::Error)]
pub enum ThumbnailerError {
    #[error("thumbnailer failed: {0}")]
    Failed(String),
}

pub fn walk_through_dir<P: AsRef<Path>>(
    path: P,
    mut func: impl FnMut(&gio::FileInfo, &gio::File),
) -> anyhow::Result<()> {
    let directory = gio::File::for_path(path.as_ref());
    if !directory.query_exists(None::<&gio::Cancellable>) {
        return Ok(());
    }

    let attributes = vec![
        gio::FILE_ATTRIBUTE_STANDARD_NAME,
        gio::FILE_ATTRIBUTE_STANDARD_TYPE,
        gio::FILE_ATTRIBUTE_STANDARD_IS_BACKUP,
        gio::FILE_ATTRIBUTE_STANDARD_IS_SYMLINK,
        gio::FILE_ATTRIBUTE_STANDARD_IS_HIDDEN,
    ]
    .iter()
    .map(|attr| attr.as_str())
    .collect::<Vec<_>>()
    .join(",");

    let enumerator = directory.enumerate_children(
        &attributes,
        gio::FileQueryInfoFlags::NONE,
        None::<&gio::Cancellable>,
    )?;

    while let Some(info) = enumerator.next_file(None::<&gio::Cancellable>)? {
        func(&info, &directory);
    }

    Ok(())
}

pub fn check_settings_folder_exists(file_name: &str) -> anyhow::Result<gio::File> {
    let mut base_path = glib::user_config_dir();
    base_path.push("sway");
    base_path.push(".generated_settings");

    if !base_path.is_dir() {
        fs::create_dir_all(&base_path)?;
    }

    let file_path = base_path.join(file_name);
    if !file_path.exists() {
        fs::File::create(&file_path)?;
    }

    Ok(gio::File::for_path(file_path))
}

pub fn write_settings(file_name: &str, lines: &[String]) -> anyhow::Result<()> {
    let file = check_settings_folder_exists(file_name)?;
    let stream = gio::OutputStream::from(file.replace(
        None::<&str>,
        false,
        gio::FileCreateFlags::REPLACE_DESTINATION,
        None::<&gio::Cancellable>,
    )?);

    stream.write_all(
        b"# GENERATED BY SWAYSETTINGS. DON'T MODIFY THIS FILE!\n",
        None::<&gio::Cancellable>,
    )?;
    for line in lines {
        stream.write_all(line.as_bytes(), None::<&gio::Cancellable>)?;
    }
    Ok(())
}

pub fn is_swaync_installed() -> bool {
    std::env::var_os("PATH")
        .and_then(|paths| {
            std::env::split_paths(&paths).find_map(|dir| {
                let candidate = dir.join("swaync");
                if candidate.exists() {
                    Some(candidate)
                } else {
                    None
                }
            })
        })
        .is_some()
}

pub fn get_swaync_config_path() -> Option<PathBuf> {
    let mut paths = Vec::new();
    let mut user_path = glib::user_config_dir();
    user_path.push("swaync");
    user_path.push("config.json");
    paths.push(user_path);

    for system_dir in glib::system_config_dirs() {
        let mut path = PathBuf::from(system_dir);
        path.push("swaync");
        path.push("config.json");
        paths.push(path);
    }

    paths.into_iter().find(|path| path.exists())
}

pub fn extract_symlink(path: &mut PathBuf) -> bool {
    let mut is_symlink = false;
    loop {
        match fs::symlink_metadata(&path) {
            Ok(metadata) if metadata.file_type().is_symlink() => match fs::read_link(&path) {
                Ok(next) => {
                    *path = next;
                    is_symlink = true;
                }
                Err(err) => {
                    log::warn!("Could not read link for path {:?}: {err}", path);
                    break;
                }
            },
            _ => break,
        }
    }
    is_symlink
}

pub fn set_gsetting(settings: &gio::Settings, name: &str, value: &Variant) -> Option<String> {
    let schema = settings.settings_schema()?;
    if !schema.has_key(name) {
        eprintln!("GSchema key \"{}\" not found!", name);
        return None;
    }

    let expected = schema.key(name).value_type();
    if expected.as_ref().as_str() != value.type_().as_str() {
        eprintln!("Set GSettings error: type mismatch");
        return None;
    }

    match value.type_().as_str() {
        "i" => {
            let val = value.get::<i32>()?;
            let _ = settings.set_int(name, val);
            Some(val.to_string())
        }
        "b" => {
            let val = value.get::<bool>()?;
            let _ = settings.set_boolean(name, val);
            Some(val.to_string())
        }
        "s" => {
            let val = value.get::<String>()?;
            let _ = settings.set_string(name, &val);
            Some(val)
        }
        "as" => {
            let val = value.get::<Vec<String>>()?;
            let refs: Vec<&str> = val.iter().map(|s| s.as_str()).collect();
            let _ = settings.set_strv(name, refs);
            Some(val.join(", "))
        }
        _ => None,
    }
}

pub fn get_gsetting(settings: &gio::Settings, name: &str, vtype: &VariantTy) -> Option<Variant> {
    let schema = settings.settings_schema()?;
    if !schema.has_key(name) {
        return None;
    }
    let expected = schema.key(name).value_type();
    if expected.as_ref().as_str() != vtype.as_str() {
        eprintln!("Get GSettings error: type mismatch for {name}");
        return None;
    }
    Some(settings.value(name))
}

pub fn generate_thumbnail<P: AsRef<Path>>(
    image_path: P,
    delete_past: bool,
    size: i32,
) -> Result<PathBuf, ThumbnailerError> {
    let file = gio::File::for_path(image_path.as_ref());
    let uri = file.uri();
    let mut checksum = glib::Checksum::new(glib::ChecksumType::Md5).unwrap();
    checksum.update(uri.as_bytes());
    let checksum = checksum.string().unwrap_or_else(|| "0".into());
    let mut cache_dir = glib::user_cache_dir();
    cache_dir.push("thumbnails");
    cache_dir.push("large");
    let checksum_path = cache_dir.join(format!("{checksum}.png"));

    if delete_past && checksum_path.exists() {
        let _ = fs::remove_file(&checksum_path);
    }

    if !checksum_path.exists() {
        let output = Command::new("glycin-thumbnailer")
            .arg("--input")
            .arg(&uri)
            .arg("--output")
            .arg(&checksum_path)
            .arg("--size")
            .arg(size.to_string())
            .output();

        match output {
            Ok(out) if out.status.success() => {}
            Ok(out) => {
                let err = String::from_utf8_lossy(&out.stderr).to_string();
                return Err(ThumbnailerError::Failed(err));
            }
            Err(err) => return Err(ThumbnailerError::Failed(err.to_string())),
        }
    }

    Ok(checksum_path)
}

pub fn calc_scaled_size(
    ref_width: f32,
    ref_height: f32,
    target_width: f32,
    target_height: f32,
) -> (f32, f32) {
    let mut new_width = target_width;
    let mut new_height = target_height;

    if (ref_width - target_width).abs() < f32::EPSILON
        || (ref_height - target_height).abs() < f32::EPSILON
    {
        return (new_width, new_height);
    }

    if target_width > 0.0 || target_height > 0.0 {
        if target_width < 0.0 {
            new_width = ref_width * target_height / ref_height;
            new_height = target_height;
        } else if target_height < 0.0 {
            new_width = target_width;
            new_height = ref_height * target_width / ref_width;
        } else if ref_height * target_width > ref_width * target_height {
            new_width = (ref_width * target_height / ref_height).round();
            new_height = target_height;
        } else {
            new_width = target_width;
            new_height = (ref_height * target_width / ref_width).round();
        }
    } else {
        if target_width > 0.0 {
            new_width = target_width;
        }
        if target_height > 0.0 {
            new_height = target_height;
        }
    }

    new_width = new_width.max(1.0);
    new_height = new_height.max(1.0);

    (new_width.floor(), new_height.floor())
}

pub fn gdk_texture_scale(
    texture: &gdk4::Texture,
    ref_width: u32,
    ref_height: u32,
    target_width: i32,
    target_height: i32,
    _filter: gsk4::ScalingFilter,
) -> Option<(gdk4::Texture, f32, f32)> {
    let (new_width, new_height) = calc_scaled_size(
        ref_width as f32,
        ref_height as f32,
        target_width as f32,
        target_height as f32,
    );

    let mut data = vec![0u8; (ref_width * ref_height * 4) as usize];
    let stride = (ref_width * 4) as usize;
    texture.download(&mut data, stride);
    let pixels = glib::Bytes::from_owned(data);
    let pixbuf = gdk_pixbuf::Pixbuf::from_bytes(
        &pixels,
        gdk_pixbuf::Colorspace::Rgb,
        true,
        8,
        ref_width as i32,
        ref_height as i32,
        (ref_width * 4) as i32,
    );

    let scaled = pixbuf
        .scale_simple(
            new_width as i32,
            new_height as i32,
            gdk_pixbuf::InterpType::Bilinear,
        )
        .unwrap_or(pixbuf);

    let width = scaled.width();
    let height = scaled.height();
    let format = if scaled.has_alpha() {
        gdk4::MemoryFormat::R8g8b8a8
    } else {
        gdk4::MemoryFormat::R8g8b8
    };
    let bytes = scaled.read_pixel_bytes();
    let stride = scaled.rowstride() as usize;
    let texture = gdk4::MemoryTexture::new(width, height, format, &bytes, stride);

    Some((texture.upcast(), new_width, new_height))
}

pub fn set_wallpaper(file_path: &str, settings: &gio::Settings) -> bool {
    if file_path.is_empty() {
        return false;
    }

    let mut dest_path = glib::user_config_dir();
    dest_path.push("swaysettings-wallpaper");

    let src = gio::File::for_path(file_path);
    let dest = gio::File::for_path(dest_path);

    if !src.query_exists(None::<&gio::Cancellable>) {
        eprintln!("File {file_path} not found or permissions missing");
        return false;
    }

    if let Err(err) = src.copy(
        &dest,
        gio::FileCopyFlags::OVERWRITE,
        None::<&gio::Cancellable>,
        None::<&mut dyn FnMut(i64, i64)>,
    ) {
        eprintln!("Copy error: {err}");
        return false;
    }

    let _ = generate_thumbnail(dest.path().expect("dest path"), true, 256);

    let _ = set_gsetting(
        settings,
        constants::SETTINGS_WALLPAPER_PATH,
        &Variant::from(file_path),
    );

    if let Some(app) = utils::wallpaper_application() {
        let config = utils::Config {
            path: file_path.to_string(),
            scale_mode: utils::get_scale_mode_gschema(settings),
            color: "#FFFFFF".to_string(),
        };

        let variant = Variant::from((
            config.path.as_str(),
            config.scale_mode as i32,
            config.color.as_str(),
        ));
        app.activate_action(constants::WALLPAPER_ACTION_NAME, Some(&variant));
    }

    true
}

pub fn get_accent_color(settings: Option<&gio::Settings>) -> gdk4::RGBA {
    let mut color_enum = 0i32;
    if let Some(settings) = settings {
        if let Some(schema) = settings.settings_schema() {
            if schema.has_key("accent-color") {
                color_enum = settings.enum_("accent-color");
            }
        }
    }

    let hex = match color_enum {
        1 => "#2190a4", // teal
        2 => "#26a269", // green
        3 => "#e5a50a", // yellow
        4 => "#ff7800", // orange
        5 => "#e01b24", // red
        6 => "#d670d6", // pink
        7 => "#9141ac", // purple
        8 => "#6f8396", // slate
        _ => "#3584e4", // blue
    };

    let mut rgba = gdk4::RGBA::new(0.0, 0.0, 0.0, 1.0);
    let color = hex.trim_start_matches('#');
    if let Ok(value) = u32::from_str_radix(color, 16) {
        rgba.set_red(((value >> 16) & 0xff) as f32 / 255.0);
        rgba.set_green(((value >> 8) & 0xff) as f32 / 255.0);
        rgba.set_blue((value & 0xff) as f32 / 255.0);
        rgba.set_alpha(1.0);
    }
    rgba
}
